area/flutter:
  - changed-files:
      - any-glob-to-any-file:
          - "applications/**"
          - "packages/**"
          - "melos.yaml"
          - "**/*.dart"
          - ".github/workflows/flutter-*.yaml"

area/go:
  - changed-files:
      - any-glob-to-any-file:
          - "services/**"
          - "go.*"
          - "**/*.go"
          - ".github/workflows/go-*.yaml"

area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/actions/**"
          - ".github/labeler.yml"

type/feature:
  - head-branch: ["^feature/", "^feat/"]

type/bug:
  - head-branch: ["^fix/", "^bugfix/", "^hotfix/"]

type/chore:
  - head-branch: ["^chore/"]

type/refactor:
  - head-branch: ["^refactor/"]

type/docs:
  - head-branch: ["^docs/"]
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**"]

type/test:
  - head-branch: ["^test/", "^tests/"]
