name: Setup Go
description: "Sets up Go environment with caching and optional private repo access"

inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "1.25.5"
  working-directory:
    description: "Path to the directory containing go.sum for caching hash"
    required: false
    default: "."
  token:
    description: "GITHUB_TOKEN for private modules access"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6.1.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    # - name: Configure Private Modules Access
    #   if: inputs.token != ''
    #   shell: bash
    #   run: |
    #     git config --global url."https://${{ inputs.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    #     echo "GOPRIVATE=github.com/my-company/*" >> $GITHUB_ENV
